apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: nitin379/flask-mongo-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo-user:mongo-pass@mongodb-service:27017/"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
